name: publish

on:
  push:
    tags:
      - '*'
  pull_request:

env:
  IMAGE_NAME: hstreamdb/haskell

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['8.6.5', '8.8.4', '8.10.2']
    steps:
      - uses: actions/checkout@v2

      - name: Build & Push images
        run: |
          docker build . -f Dockerfile.dev --build-arg GHC=${{ matrix.ghc }} --tag hstreamdb/haskell:${{ matrix.ghc }}

          if [ "${{ github.event_name }}" == 'push' ]; then
            if [ "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
              echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
              docker push hstreamdb/haskell:${{ matrix.ghc }}
              if [ "${{ matrix.ghc }}" == '8.10.2' ]; then
              echo "Push latest tag with ghc: ${{ matrix.ghc }}"
                docker tag hstreamdb/haskell:${{ matrix.ghc }} hstreamdb/haskell:latest
                docker push hstreamdb/haskell:latest
              fi
            else
              echo "No such secrets, ignored."
            fi
          fi
